version: "3.7"

services:
  api:
    build: .
    container_name: papyroAPI
    command: uvicorn src.main:app --host 0.0.0.0 --reload --reload-dir=src --proxy-headers 
    volumes:
      - .:/papyroAPI
    ports:
      - $PYTHON_LOCAL_PORT:$PYTHON_DOCKER_PORT
    depends_on:
      - db
    environment:
      DB_UPSTREAM: http://host.docker.internal:8000
    env_file:
      - .env
  db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    ports:
      - $POSTGRES_PORT:$POSTGRES_DOCKER_PORT
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
volumes:
  postgres_data: