version: "3.7"

services:
  api:
    build: .
    container_name: papyroAPI
    command: uvicorn src.main:app --proxy-headers --host 0.0.0.0 --reload --reload-dir=src
    volumes:
     - .:/code
    ports:
      - $PYTHON_LOCAL_PORT:$PYTHON_DOCKER_PORT
    depends_on:
       - db
    env_file:
      - .env

  db:
     image: postgres:14
     restart: always
     environment:
       - POSTGRES_USER=$POSTGRES_USER
       - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
       - POSTGRES_DB=$POSTGRES_DB
     ports:
      - $POSTGRES_PORT:$POSTGRES_DOCKER_PORT
     env_file:
      - .env
