version: "3.9"

services:
  web:
    build: .
    command: uvicorn src.main:app --reload --reload-dir=src
    volumes:
      - .:/papyroAPI
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: