"""Nova coluna blablabla

Revision ID: 03503ce5e80f
Revises: 2ce165e6ba43
Create Date: 2022-03-09 23:49:15.882380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03503ce5e80f'
down_revision = '2ce165e6ba43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
