"""boa noite

Revision ID: 0760a96f7dde
Revises: cda71427f81d
Create Date: 2022-03-29 01:45:10.393166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0760a96f7dde'
down_revision = 'cda71427f81d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
