"""add date on table friend

Revision ID: 087fb1f9e1db
Revises: c37fccaae33c
Create Date: 2022-08-14 23:25:37.568506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '087fb1f9e1db'
down_revision = 'c37fccaae33c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friend', sa.Column('date', sa.DateTime(), nullable=True))
    op.add_column('like', sa.Column('date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('friend', 'date')
    op.drop_column('like', 'date')
    # ### end Alembic commands ###
