"""agora vai funcionar 1

Revision ID: 0ae4879a3c01
Revises: 354365d081c1
Create Date: 2022-02-24 02:42:17.850947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ae4879a3c01'
down_revision = '354365d081c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
