"""Nova coluna blablabla

Revision ID: 12a8b4e169e2
Revises: c6554435a424
Create Date: 2022-03-19 18:00:53.802137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12a8b4e169e2'
down_revision = 'c6554435a424'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
