"""Nova coluna blablabla1

Revision ID: 1e461bfa5eb3
Revises: e38668f6342a
Create Date: 2022-03-22 00:57:45.405781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e461bfa5eb3'
down_revision = 'e38668f6342a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
