"""Nova coluna blablablaaa

Revision ID: 254eb0b2883c
Revises: 1e461bfa5eb3
Create Date: 2022-03-24 01:52:20.816548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '254eb0b2883c'
down_revision = '1e461bfa5eb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
