"""Nova coluna blablabla

Revision ID: 28ee19003458
Revises: 12a8b4e169e2
Create Date: 2022-03-19 18:51:19.640765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28ee19003458'
down_revision = '12a8b4e169e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
