"""tb usuario modificada

Revision ID: 2afc2f54e301
Revises: 9e5bae3fdd8b
Create Date: 2022-01-29 12:01:11.952473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2afc2f54e301'
down_revision = '9e5bae3fdd8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_nascimento', sa.DateTime(), nullable=True))
        batch_op.drop_column('dataNascimento')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dataNascimento', sa.DATETIME(), nullable=True))
        batch_op.drop_column('data_nascimento')

    # ### end Alembic commands ###
