"""update tb isbn_livro column isbn

Revision ID: 2ce165e6ba43
Revises: 9acc167c428c
Create Date: 2022-03-05 17:49:30.304787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ce165e6ba43'
down_revision = '9acc167c428c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('livro_isbn', 'isbn',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=13),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('livro_isbn', 'isbn',
               existing_type=sa.String(length=13),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    # ### end Alembic commands ###
