"""correcao na tb usuario_genero

Revision ID: 354365d081c1
Revises: 0a3d3fb6ce08
Create Date: 2022-02-24 02:13:08.582773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '354365d081c1'
down_revision = '0a3d3fb6ce08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
