"""tb usuario modificada

Revision ID: 37adb3272abf
Revises: c6d66a49774e
Create Date: 2022-01-29 12:17:26.085057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37adb3272abf'
down_revision = 'c6d66a49774e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
