"""Novas tabelas livro_isbn, autor, livro_autores, papel

Revision ID: 423eaa7b3d0e
Revises: 96a380a2e935
Create Date: 2022-02-16 19:26:05.444311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '423eaa7b3d0e'
down_revision = '96a380a2e935'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('autor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_autor_id'), 'autor', ['id'], unique=False)
    op.create_table('papel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_papel_id'), 'papel', ['id'], unique=False)
    op.create_table('livro_autores',
    sa.Column('fk_autor', sa.Integer(), nullable=False),
    sa.Column('fk_livro', sa.Integer(), nullable=False),
    sa.Column('fk_papel', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_autor'], ['autor.id'], ),
    sa.ForeignKeyConstraint(['fk_livro'], ['livro.id'], ),
    sa.ForeignKeyConstraint(['fk_papel'], ['papel.id'], ),
    sa.PrimaryKeyConstraint('fk_autor', 'fk_livro')
    )
    op.create_table('livro_isbn',
    sa.Column('isbn', sa.String(length=10), nullable=False),
    sa.Column('fk_livro', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_livro'], ['livro.id'], ),
    sa.PrimaryKeyConstraint('isbn')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('livro_isbn')
    op.drop_table('livro_autores')
    op.drop_index(op.f('ix_papel_id'), table_name='papel')
    op.drop_table('papel')
    op.drop_index(op.f('ix_autor_id'), table_name='autor')
    op.drop_table('autor')
    # ### end Alembic commands ###
