"""add tabela amigo

Revision ID: 4a46a5f3d46d
Revises: e10fa1e696db
Create Date: 2022-04-01 22:21:36.795386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a46a5f3d46d'
down_revision = 'e10fa1e696db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amigo',
    sa.Column('fk_origem', sa.Integer(), nullable=False),
    sa.Column('fk_destino', sa.Integer(), nullable=False),
    sa.Column('pendente', sa.Boolean(), nullable=True),
    sa.Column('ignorado', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['fk_destino'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['fk_origem'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('fk_origem', 'fk_destino')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('amigo')
    # ### end Alembic commands ###
