"""Nova tabela avalicao v2

Revision ID: 4bb6305d3c9e
Revises: fbeab0850dbc
Create Date: 2022-03-26 23:03:12.886906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bb6305d3c9e'
down_revision = 'fbeab0850dbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('avaliacao', 'data_criacao',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('avaliacao', 'data_criacao',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
    # ### end Alembic commands ###
