"""new column 'identified' on table book

Revision ID: 5722d93529ab
Revises: f0e1cf771bdc
Create Date: 2022-07-23 21:34:59.869801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5722d93529ab'
down_revision = 'f0e1cf771bdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('identified', sa.String(length=25), nullable=True))
    op.add_column('comment', sa.Column('fk_rate', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comment', 'rate', ['fk_rate'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_column('comment', 'fk_rate')
    op.drop_column('book', 'identified')
    # ### end Alembic commands ###
