"""Nova coluna blablabla1

Revision ID: 678fe493132f
Revises: 03503ce5e80f
Create Date: 2022-03-10 00:09:10.068711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '678fe493132f'
down_revision = '03503ce5e80f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
