"""criacao tabela genero e usuario_genero

Revision ID: 758026b6de47
Revises: f6a7b177ca02
Create Date: 2022-02-15 02:13:47.950467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '758026b6de47'
down_revision = 'f6a7b177ca02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genero',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('genero', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_genero_id'), 'genero', ['id'], unique=False)
    op.create_table('usuario_genero',
    sa.Column('fk_genero', sa.Integer(), nullable=False),
    sa.Column('fk_usuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fk_genero'], ['genero.id'], ),
    sa.ForeignKeyConstraint(['fk_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('fk_genero', 'fk_usuario')
    )
    op.create_unique_constraint(None, 'usuario', ['apelido'])
    op.drop_column('usuario', 'teste1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('teste1', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'usuario', type_='unique')
    op.drop_table('usuario_genero')
    op.drop_index(op.f('ix_genero_id'), table_name='genero')
    op.drop_table('genero')
    # ### end Alembic commands ###
