"""add coluna 'chave' nas tabelas livro e autor

Revision ID: 76080327736c
Revises: e10fa1e696db
Create Date: 2022-04-06 01:36:54.285244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76080327736c'
down_revision = 'e10fa1e696db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amigo',
    sa.Column('fk_origem', sa.Integer(), nullable=False),
    sa.Column('fk_destino', sa.Integer(), nullable=False),
    sa.Column('pendente', sa.Boolean(), nullable=True),
    sa.Column('ignorado', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['fk_destino'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['fk_origem'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('fk_origem', 'fk_destino')
    )
    op.create_table('mensagem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.String(length=255), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('fk_origem', sa.Integer(), nullable=True),
    sa.Column('fk_destino', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_destino'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['fk_origem'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mensagem_id'), 'mensagem', ['id'], unique=False)
    op.add_column('autor', sa.Column('chave', sa.String(length=50), nullable=True))
    op.add_column('livro', sa.Column('chave', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('livro', 'chave')
    op.drop_column('autor', 'chave')
    op.drop_index(op.f('ix_mensagem_id'), table_name='mensagem')
    op.drop_table('mensagem')
    op.drop_table('amigo')
    # ### end Alembic commands ###
