"""fixed table mensagem

Revision ID: 79e1e9923db9
Revises: e548cc6c3d4b
Create Date: 2022-04-04 18:33:28.392503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79e1e9923db9'
down_revision = 'e548cc6c3d4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mensagem', 'fk_origem',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('mensagem', 'fk_destino',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mensagem', 'fk_destino',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('mensagem', 'fk_origem',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
