"""Nova coluna blablabla

Revision ID: 7a9f9bf60b78
Revises: b2afaa06f462
Create Date: 2022-03-16 22:53:10.308277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a9f9bf60b78'
down_revision = 'b2afaa06f462'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario_livro',
    sa.Column('fk_grupo', sa.Integer(), nullable=False),
    sa.Column('fk_usuario', sa.Integer(), nullable=False),
    sa.Column('fk_cargo', sa.Integer(), nullable=True),
    sa.Column('data_entrada', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['fk_cargo'], ['cargo.id'], ),
    sa.ForeignKeyConstraint(['fk_grupo'], ['grupo.id'], ),
    sa.ForeignKeyConstraint(['fk_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('fk_grupo', 'fk_usuario')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario_livro')
    # ### end Alembic commands ###
