"""fix versions

Revision ID: 7c1a393d80fc
Revises: c320c38372b8
Create Date: 2022-07-26 13:33:40.354970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c1a393d80fc'
down_revision = 'c320c38372b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('fk_rate', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comment', 'rate', ['fk_rate'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_column('comment', 'fk_rate')
    op.drop_column('book', 'identified')
    # ### end Alembic commands ###
