"""Novas tbs grupo, cargo, usuario_grupo

Revision ID: 89488736c519
Revises: 0ae4879a3c01
Create Date: 2022-03-02 19:42:47.899539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89488736c519'
down_revision = '0ae4879a3c01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cargo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cargo', sa.String(length=127), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cargo_id'), 'cargo', ['id'], unique=False)
    op.create_table('grupo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('foto', sa.String(length=255), nullable=True),
    sa.Column('descricao', sa.String(length=1023), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grupo_id'), 'grupo', ['id'], unique=False)
    op.create_table('usuario_grupo',
    sa.Column('fk_grupo', sa.Integer(), nullable=False),
    sa.Column('fk_usuario', sa.Integer(), nullable=False),
    sa.Column('fk_cargo', sa.Integer(), nullable=True),
    sa.Column('data_entrada', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['fk_cargo'], ['cargo.id'], ),
    sa.ForeignKeyConstraint(['fk_grupo'], ['grupo.id'], ),
    sa.ForeignKeyConstraint(['fk_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('fk_grupo', 'fk_usuario')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario_grupo')
    op.drop_index(op.f('ix_grupo_id'), table_name='grupo')
    op.drop_table('grupo')
    op.drop_index(op.f('ix_cargo_id'), table_name='cargo')
    op.drop_table('cargo')
    # ### end Alembic commands ###
