"""remove english_name, add tb friend

Revision ID: 8b7cec397250
Revises: ee17e3f862d5
Create Date: 2022-07-21 01:06:51.345189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b7cec397250'
down_revision = 'ee17e3f862d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friend',
    sa.Column('pending', sa.Boolean(), nullable=True),
    sa.Column('ignored', sa.Boolean(), nullable=True),
    sa.Column('fk_origin', sa.Integer(), nullable=False),
    sa.Column('fk_destiny', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fk_destiny'], ['user.id'], ),
    sa.ForeignKeyConstraint(['fk_origin'], ['user.id'], ),
    sa.PrimaryKeyConstraint('fk_origin', 'fk_destiny')
    )
    op.drop_column('genre', 'english_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('genre', sa.Column('english_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_table('friend')
    # ### end Alembic commands ###
