"""Nova tabela livro

Revision ID: 96a380a2e935
Revises: 758026b6de47
Create Date: 2022-02-16 19:09:43.421618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96a380a2e935'
down_revision = '758026b6de47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('livro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=True),
    sa.Column('ano', sa.Date(), nullable=True),
    sa.Column('nota', sa.Integer(), nullable=True),
    sa.Column('sinopse', sa.Text(), nullable=True),
    sa.Column('capa', sa.String(length=255), nullable=True),
    sa.Column('fk_genero', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_genero'], ['genero.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_livro_id'), 'livro', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_livro_id'), table_name='livro')
    op.drop_table('livro')
    # ### end Alembic commands ###
