"""add fk cargo no grupo

Revision ID: 9acc167c428c
Revises: 89488736c519
Create Date: 2022-03-02 21:24:53.000490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9acc167c428c'
down_revision = '89488736c519'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grupo', sa.Column('fk_cargo', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'grupo', 'cargo', ['fk_cargo'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'grupo', type_='foreignkey')
    op.drop_column('grupo', 'fk_cargo')
    # ### end Alembic commands ###
