"""tb usuario modificada

Revision ID: 9e545954847b
Revises: 37adb3272abf
Create Date: 2022-01-30 21:56:36.716553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e545954847b'
down_revision = '37adb3272abf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
