"""test

Revision ID: 9e5bae3fdd8b
Revises: 
Create Date: 2022-01-24 21:11:52.595945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e5bae3fdd8b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tb_usuario_id', table_name='tb_usuario')
    op.drop_table('tb_usuario')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_usuario',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('nome', sa.VARCHAR(), nullable=True),
    sa.Column('apelido', sa.VARCHAR(), nullable=True),
    sa.Column('data_nascimento', sa.DATETIME(), nullable=True),
    sa.Column('foto', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_tb_usuario_id', 'tb_usuario', ['id'], unique=False)
    # ### end Alembic commands ###
