"""relacionamente entre as tabelas grupo e usuario

Revision ID: b2afaa06f462
Revises: d0eb05fa9ee0
Create Date: 2022-03-16 20:52:51.836176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2afaa06f462'
down_revision = 'd0eb05fa9ee0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('grupo_fk_cargo_fkey', 'grupo', type_='foreignkey')
    op.drop_column('grupo', 'fk_cargo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grupo', sa.Column('fk_cargo', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('grupo_fk_cargo_fkey', 'grupo', 'cargo', ['fk_cargo'], ['id'])
    # ### end Alembic commands ###
