"""Nova coluna blablabla

Revision ID: c6554435a424
Revises: 1a59d0e3bf84
Create Date: 2022-03-18 00:39:12.629160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6554435a424'
down_revision = '1a59d0e3bf84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
