"""kkk

Revision ID: cb63fea4a3cf
Revises: 0760a96f7dde
Create Date: 2022-03-29 02:50:44.115950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb63fea4a3cf'
down_revision = '0760a96f7dde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
