"""oi

Revision ID: cda71427f81d
Revises: eb308846c911
Create Date: 2022-03-29 00:36:01.268355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cda71427f81d'
down_revision = 'eb308846c911'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comentario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nota', sa.Integer(), nullable=True),
    sa.Column('texto', sa.String(length=255), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('fk_usuario', sa.Integer(), nullable=True),
    sa.Column('fk_livro', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_livro'], ['livro.id'], ),
    sa.ForeignKeyConstraint(['fk_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comentario_id'), 'comentario', ['id'], unique=False)
    op.create_table('likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_comentario', sa.Integer(), nullable=True),
    sa.Column('fk_avaliacao', sa.Integer(), nullable=True),
    sa.Column('fk_usuario', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_avaliacao'], ['avaliacao.id'], ),
    sa.ForeignKeyConstraint(['fk_comentario'], ['comentario.id'], ),
    sa.ForeignKeyConstraint(['fk_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_likes_id'), 'likes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_likes_id'), table_name='likes')
    op.drop_table('likes')
    op.drop_index(op.f('ix_comentario_id'), table_name='comentario')
    op.drop_table('comentario')
    # ### end Alembic commands ###
