"""Nova coluna blablabl11a

Revision ID: d0eb05fa9ee0
Revises: f2fa37d816dc
Create Date: 2022-03-13 20:21:29.446170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0eb05fa9ee0'
down_revision = 'f2fa37d816dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('descricao', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'descricao')
    # ### end Alembic commands ###
