"""update

Revision ID: e10fa1e696db
Revises: cb63fea4a3cf
Create Date: 2022-04-01 01:04:34.933525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e10fa1e696db'
down_revision = 'cb63fea4a3cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
