"""Nova coluna blablabla

Revision ID: e38668f6342a
Revises: 28ee19003458
Create Date: 2022-03-22 00:50:40.146215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e38668f6342a'
down_revision = '28ee19003458'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
