"""Nova coluna blablablaaaa

Revision ID: e452880c0aea
Revises: 678fe493132f
Create Date: 2022-03-12 19:45:54.304817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e452880c0aea'
down_revision = '678fe493132f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
