"""create table mensagem

Revision ID: e548cc6c3d4b
Revises: 4a46a5f3d46d
Create Date: 2022-04-04 18:26:39.921703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e548cc6c3d4b'
down_revision = '4a46a5f3d46d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mensagem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.String(length=255), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('fk_origem', sa.Integer(), nullable=False),
    sa.Column('fk_destino', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fk_destino'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['fk_origem'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id', 'fk_origem', 'fk_destino')
    )
    op.create_index(op.f('ix_mensagem_id'), 'mensagem', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mensagem_id'), table_name='mensagem')
    op.drop_table('mensagem')
    # ### end Alembic commands ###
