"""aa

Revision ID: eb308846c911
Revises: 4bb6305d3c9e
Create Date: 2022-03-26 23:19:11.981366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb308846c911'
down_revision = '4bb6305d3c9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
