"""fix

Revision ID: ee17e3f862d5
Revises: 7188fb201201
Create Date: 2022-07-20 18:50:21.036687

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ee17e3f862d5'
down_revision = '7188fb201201'
branch_labels = None
depends_on = 'c320c38372b8'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('genre', sa.Column('english_name', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('birthday', sa.Date(), nullable=True))
    op.drop_column('user', 'date')
    op.alter_column('user_book', 'date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_book', 'date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.add_column('user', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('user', 'birthday')
    op.drop_column('genre', 'english_name')
    # ### end Alembic commands ###
