"""Nova coluna blablablaaaa1

Revision ID: f2fa37d816dc
Revises: e452880c0aea
Create Date: 2022-03-12 22:15:47.294221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2fa37d816dc'
down_revision = 'e452880c0aea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
