"""test23123

Revision ID: f6a7b177ca02
Revises: 984875061d76
Create Date: 2022-02-10 00:27:46.836314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6a7b177ca02'
down_revision = '984875061d76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('teste1', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'teste1')
    # ### end Alembic commands ###
