"""Nova tabela avalicao

Revision ID: fbeab0850dbc
Revises: 254eb0b2883c
Create Date: 2022-03-26 23:01:15.733459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbeab0850dbc'
down_revision = '254eb0b2883c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avaliacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.String(length=255), nullable=True),
    sa.Column('data_criacao', sa.Date(), nullable=True),
    sa.Column('nota', sa.Integer(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('fk_usuario', sa.Integer(), nullable=True),
    sa.Column('fk_livro', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_livro'], ['livro.id'], ),
    sa.ForeignKeyConstraint(['fk_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_avaliacao_id'), 'avaliacao', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_avaliacao_id'), table_name='avaliacao')
    op.drop_table('avaliacao')
    # ### end Alembic commands ###
